# Zabbix Exporter for Prometheus simular Node_Exporter
db_exporter_for_prometheus:
    # спецификация
    # наименование проекта
    PROJECT:
    # JDBC URL
    URL :
    # путь к библиотеке
    LIB_PATH :
    # наименование Java класса
    CLASS : org.apache.hive.jdbc.HiveDriver
    # имя
    USERNAME :
    # пароль
    PASSWORD :
    # список метрик
    METRICS:
    - value1_change_cnt
    - value2_change_cnt
    # список баз данных
    DBNAME:
      - base1
      - base2
    # список скриптов
    SCRIPT:
      - sql: |
          with pre as (
          select *
          from base1.change_cnt value
          order by value.date desc
          limit 1
          )
          select cnt
          from pre
      - sql: |
          with pre as (
          select *
          from base2.change_cnt value
          order by value.date desc
          limit 1
          )
          select cnt
          from pre